
package com.tws.lab.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CarServiceFault", targetNamespace = "http://soap.lab.tws.com/")
public class CarCrudException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CarCrudException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CarCrudException_Exception(String message, CarCrudException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CarCrudException_Exception(String message, CarCrudException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.tws.lab.soap.CarCrudException
     */
    public CarCrudException getFaultInfo() {
        return faultInfo;
    }

}
