
package com.tws.lab.soap;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CarWebService", targetNamespace = "http://soap.lab.tws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.tws.lab.soap.Car>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchCars", targetNamespace = "http://soap.lab.tws.com/", className = "com.tws.lab.soap.SearchCars")
    @ResponseWrapper(localName = "searchCarsResponse", targetNamespace = "http://soap.lab.tws.com/", className = "com.tws.lab.soap.SearchCarsResponse")
    @Action(input = "http://soap.lab.tws.com/CarWebService/searchCarsRequest", output = "http://soap.lab.tws.com/CarWebService/searchCarsResponse")
    public List<Car> searchCars(
        @WebParam(name = "arg0", targetNamespace = "")
        CarListRequestDto arg0);

}
